{
  "hash": "aea5f4acc402ca2547498ab7158bc889",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cats vs. Dogs\"\ndescription: |\n  Woofs and meows, which will prevail?\ndate: '2025-12-08'\nimage: \"catsvdogs.jpg\"\ncategories:\n    - Pets\nformat: html\ntoc: true\nlightbox: true\nexecute:\n  echo: false\n  warning: false\n  error: false\n  message: false\n---\n\n::: {.cell}\n\n:::\n\n\n\n# The age old question, \"cats or dogs\", has long been debated. From ancient times, both have been revered as companions, utilized for their hunting prowess, and appreciated for their beauty. But...... how do we feel about them at EPA?\n\n## Counts and Shares\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Votes and shares for Cats vs Dogs.](index_files/figure-html/fig-bar-1.png){#fig-bar width=576}\n:::\n:::\n\n\n\nDogs share: 66.7%, Cats share: 33.3%.\nVote margin (Dogs − Cats): 14 votes = 33.3%.\n\n## Statistical difference from 50/50\n\nTesting Cats proportion p against 0.5 using an exact binomial test.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  14 and N\nnumber of successes = 14, number of trials = 42, p-value = 0.04356\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.1956680 0.4954875\nsample estimates:\nprobability of success \n             0.3333333 \n```\n\n\n:::\n:::\n\n\n\nTwo‑sided p‑value: 0.0436\n95% exact CI for p(Cats): 0.196 to 0.495\n\nExpress the Dogs lead as a margin in share terms, margin = p(Dogs) − p(Cats) = 1 − 2p(Cats). The corresponding 95% CI:\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.608663904 0.009025071\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\n\nEven the lower bound of the margin is positive, indicating a clear preference for Dogs.\n\nHow many flips would change the winner?\n\nTo tie, you’d need 7 votes to flip (7 Dogs → Cats).\nTo give Cats a lead, you’d need 8 flips (8 votes).\n\n## How unusual is 14-28 under a fair 50/50 world?\n\nUnder p = 0.5 with N = 42, the probability to be at least this far from 50/50 (two‑sided) is the binomial test p‑value.\n\nWe can also simulate the Cats counts under 50/50:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Simulated Cats counts under a 50/50 world (10,000 polls, N = 42). The observed 14 is marked.](index_files/figure-html/fig-sim-null-1.png){#fig-sim-null width=672}\n:::\n:::\n\n\n\nFraction of simulations at least as extreme (two‑sided):\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.045\n```\n\n\n:::\n:::\n\n\n\n## Likelihood and Bayesian view for the Cats share\n\nBinomial likelihood for p(Cats) given 14 out of 42 votes:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Binomial likelihood L(p) for p(Cats) given 14/42 (scaled to max = 1).](index_files/figure-html/fig-likelihood-1.png){#fig-likelihood width=576}\n:::\n:::\n\n\n\nWith a flat prior Beta(1,1), the posterior is Beta(15,29). Credible interval and the probability Cats < 0.5 (i.e., Dogs lead):\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Posterior for p(Cats) with Beta(1,1) prior (posterior = Beta(15,29)).](index_files/figure-html/fig-posterior-1.png){#fig-posterior width=576}\n:::\n:::\n\n\n\n95% credible interval for p(Cats): [0.210, 0.485]\n\nPosterior probability Dogs lead (p(Cats) < 0.5): 0.9842\n\nPosterior predictive for a repeat poll of size 42: chance Cats win, tie, or Dogs win.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\npp_cat_win     pp_tie pp_dog_win \n   0.05165    0.02770    0.92065 \n```\n\n\n:::\n:::\n\n\n\nBayes factor for “not 50/50” vs “p = 0.5” using Jeffreys prior Beta(0.5,0.5).\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.319843\n```\n\n\n:::\n:::\n\n\n\nBF10 > 1 supports “not 50/50”; values around 3–10 are often called “moderate” evidence.\n\n## Effect sizes and ratios\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nrisk_difference      risk_ratio       odds_dogs        cohens_h \n      0.3333333       2.0000000       2.0000000       0.6796738 \n```\n\n\n:::\n:::\n\n\n\nDogs lead by 33.3% in share.\nDogs have about 2:1 the share of Cats and odds about 2:1.\nCohen’s h ≈ 0.68 (medium‑to‑large difference; 0.2 small, 0.5 medium, 0.8 large).\n\n## Waffle chart (one square per voter)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Waffle chart: 42 voters, Cats = 14, Dogs = 28.](index_files/figure-html/fig-waffle-1.png){#fig-waffle width=576}\n:::\n:::\n\n\n\n# Takeaways\n\nDogs win clearly: 28–14 yields a Dogs margin of 33.3%.\n\nExact binomial test vs 50/50 is significant (p ≈ 0.0436), and the 95% CI for p(Cats) lies below 0.5.\n\nA fair coin process would rarely produce a result this lopsided for N = 42.\n\nBayesian analysis strongly favors a Dogs lead and predicts Dogs would likely win a same‑size repeat poll.\n\nTo tie you’d need 7 flips; to flip the winner, 8 flips.\n\n# Unfortunately, its a resounding vote for dogs. Cats, better luck next time.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}